name: 更新GitHub Readme Stats卡片

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card(light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=buefy&locale=cn&show_icons=true
          path: profile/stats_light.svg
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate stats card(dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=vue-dark&locale=cn&show_icons=true
          path: profile/stats_dark.svg
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card(light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=buefy&locale=cn&layout=compact
          path: profile/top-langs_light.svg
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card(dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=vue-dark&locale=cn&layout=compact
          path: profile/top-langs_dark.svg
          # token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=readme-tools&repo=github-readme-stats
      #     path: profile/pin-readme-tools-github-readme-stats.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push